version: "3.7"
services:
  nginx:
    container_name: js-box-nginx
    image: nginx:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./nginx:/app/nginx/
      - ./logs/nginx:/app/logs
    ports:
      - "${JS_DOCK_NGINX_PORT}:8000"
    expose:
      - ${JS_DOCK_NGINX_PORT}
    environment:
      - NGINX_HOST=${JS_DOCK_NGINX_HOST}
      - NGINX_PORT=8000
    command: /bin/bash -c "envsubst < /app/nginx/nginx-${JS_DOCK_ENVIRONMENT}.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - client
      - api
    networks:
      - network
  client:
    container_name: js-box-client
    build:
      context: .
      dockerfile: .docker-client-${JS_DOCK_ENVIRONMENT}.dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${JS_DOCK_ENVIRONMENT}
    stdin_open: true
    volumes:
      - ./client:/app/client/
      - /app/client/node_modules
      - /app/client/build
      - ./logs/client:/app/logs
    depends_on:
      - api
    networks:
      - network
  api:
    container_name: js-box-api
    build:
      context: .
      dockerfile: .docker-api-${JS_DOCK_ENVIRONMENT}.dockerfile
    restart: always
    user: "node"
    env_file:
      - ./.env
    volumes:
      - ./api:/app/api/
      - /app/api/node_modules
      - ./logs/api:/app/logs
    privileged: true
    depends_on:
      - mongodb
    networks:
      - network
  mongodb:
    container_name: js-box-mongodb
    image: mongo:latest
    restart: always
    ports:
      - ${JS_DOCK_MONGODB_PORT}:27017
    networks:
      - network
networks:
    network:
        driver: bridge
