version: "3.7"
services:
  nginx:
    container_name: js-dock-nginx
    image: nginx:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./nginx:/app/nginx/
      - ./logs:/app/logs
    ports:
      - "${JS_DOCK_NGINX_PORT}:8000"
    expose:
      - ${JS_DOCK_NGINX_PORT}
    environment:
      - NGINX_HOST=${JS_DOCK_NGINX_HOST}
      - NGINX_PORT=8000
    command: /bin/bash -c "envsubst < /app/nginx/nginx-${JS_DOCK_ENVIRONMENT}.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - client
    networks:
      - js-dock-network
  client:
    container_name: js-dock-client
    build:
      context: .
      dockerfile: .docker-client-${JS_DOCK_ENVIRONMENT}.dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./nginx:/app/nginx/
      - ./logs:/app/logs
    command: /bin/bash -c "envsubst < /app/nginx/client-${JS_DOCK_ENVIRONMENT}.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - js-dock-network
  api:
    container_name: js-dock-api
    build:
      context: .
      dockerfile: .docker-api-${JS_DOCK_ENVIRONMENT}.dockerfile
    restart: always
    user: "node"
    env_file:
      - ./.env
    volumes:
      - ./api:/app/api/
      - ./logs:/app/logs
    privileged: true
    networks:
      - js-dock-network
  mongodb:
    container_name: js-dock-mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - js-dock-network
networks:
    js-dock-network:
        driver: bridge
