version: "2"
services:
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client-${JS_BOX_CLIENT}:/app/client/
    # Expose the port for development purpose
    ports:
      - "${JS_BOX_DEV_CLIENT_PORT}:3000"
  api:
    volumes:
      - ./api:/app/api/
    # Expose the port for development purpose
    ports:
      - "${JS_BOX_DEV_API_PORT}:4000"

